function toggleFullScreen(){document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement?document.exitFullscreen?document.exitFullscreen():document.msExitFullscreen?document.msExitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitExitFullscreen&&document.webkitExitFullscreen():document.documentElement.requestFullscreen?document.documentElement.requestFullscreen():document.documentElement.msRequestFullscreen?
document.documentElement.msRequestFullscreen():document.documentElement.mozRequestFullScreen?document.documentElement.mozRequestFullScreen():document.documentElement.webkitRequestFullscreen&&document.documentElement.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}function check_window_size(){gl.canvas.width=160;gl.viewportWidth=160;gl.canvas.height=160;gl.canvas.style.height="100%";gl.viewportHeight=160;gl.canvas.style.position="fixed"}function animate(){lastTime=(new Date).getTime()}
function clearKeys(){for(var a=[KEY_LEFT,KEY_RIGHT,KEY_UP,KEY_DOWN,KEY_SPACE],b=0;b<a.length;b++)currentlyPressedKeys[a[b]]=!1}function PlaySound(a,b){}function Level(a){this.type="Level";this.t=a;this.mode=0;this.grid=64;this.sz=40;this.backup=this.levnum=this.loaded=0;this.snapshots=[];for(a=0;a<MAXBACKUPS;a++)this.snapshots[a]=0}Level.prototype.block=function(a,b){return this.L[a*this.grid+b][0]};Level.prototype.dist=function(a,b){var c=a.x-b.x,d=a.y-b.y;return Math.sqrt(c*c+d*d)};
Level.prototype.pt=function(a,b,c,d,g){var f=[BSEA,null,0,0,0];0<=a&&a<this.w&&0<=b&&b<this.h&&(f=this.L[a*this.grid+b]);var e=this.sz*(f[2]+c*f[3]+d*f[4]);f[0]==BSEA&&(e=1*-this.sz);a=[this.sz*(a+c),this.sz*(b+d),e];if(f[1]){if(!g||f[1]==g)return a;a[2]=this.groundpt(f[1])[2];for(f=f[1];f&&f!=g;f=f.contents)this.dist(f,g)<.8*this.sz&&(a[2]+=objectHeights[f.type]*this.sz)}return a};
Level.prototype.groundpt=function(a){var b=a.x,c=a.y,b=b/this.sz,c=c/this.sz,d=Math.floor(b),g=Math.floor(c);return this.pt(d,g,b-d,c-g,a)};Level.prototype.squareHeight=function(a,b,c){a=this.L[a];b=this.sz*(a[2]+b*a[3]+c*a[4]);a[0]==BSEA&&(b=1*-this.sz);return b};Level.prototype.calcPotential=function(a){return this.squareHeight(a.square,.5,.5)+this.stackHeight(a)};Level.prototype.stackHeight=function(a){var b=0;for(a=a.standingon;a;a=a.standingon)b+=objectHeights[a.type]*this.sz;return b};
Level.prototype.makeModel=function(){for(var a=[],b=[],c=[],d=this.w,g=this.h,f=[[0,0],[1,0],[1,1],[0,1]],e=[0,4,1,2,6,7,7,8,9,9,15,7],k=0;k<g;k++)for(var l=0;l<d;l++){var m=a.length,n=this.block(l,k);if(n!=BSEA){for(var n=e[n],s=.25*(n&3),t=.25*(n>>2),n=0;4>n;n++){var q=f[n][0],r=f[n][1];a.push(this.pt(l,k,q,r));b.push([s+.25*q,t+.25*r,1])}c.push([m,m+1,m+2]);c.push([m,m+2,m+3]);for(n=0;4>n;n++){var q=f[n][0],r=f[n][1],m=f[n+1&3][0],x=f[n+1&3][1],u=q+m-1,v=r+x-1,s=this.pt(l,k,q,r),t=this.pt(l,k,
m,x),q=this.pt(l+u,k+v,q-u,r-v),r=this.pt(l+u,k+v,m-u,x-v);if(s[2]>q[2]+.1||t[2]>r[2]+.1){m=a.length;a.push(s,t,r,q);for(q=0;4>q;q++)b.push([.25+.25*f[q][0],.75+.25*f[q][1],.6]);c.push([m,m+2,m+1]);c.push([m,m+3,m+2])}}}}this.buf=new Buffer(a,b,c)};Level.prototype.drawTiles=function(a){this.t.select();level.loaded&&this.buf.draw(a)};
Level.prototype.drawObjects=function(a,b,c){if(level.loaded)for(b=0;b<this.P.length;b++){var d=this.P[b];!(d.type in models)||!c&&d.type==CHEST||c&&d.type!=CHEST||(world.identity(),world.translate(level.groundpt(d)),1<Math.abs(d.thetaf)&&world.rotate(d.thetaf),0<d.bounce&&world.rotatex(2*d.bounce),a.selectWorld(world.V),models[d.type].draw(a),d.type==PENG&&0<d.numfish&&(world.translate([0,0,40]),a.selectWorld(world.V),models[FISHPAIL].draw(a)))}};
Level.prototype.drawFragments=function(a){if(level.loaded)for(var b=0;b<this.P.length;b++){var c=this.P[b];c.type==FRAGMENT&&(world.identity(),world.translate([c.x,c.y,c.d]),a.selectWorld(world.V),a.blend(c.steps),expl.draw(a))}};Level.prototype.advanceSnapshot=function(){this.backup=this.backup+1&MAXBACKUPS-1;return this.snapshots[this.backup]};
Level.prototype.snapshot=function(){for(var a=[],b=this.L,c=0;c<this.h;c++)for(var d=0;d<this.w;d++){var g=d*this.grid+c;a[g]=b[g].slice(0)}b=[];d=this.P;for(c=0;c<d.length;c++){b[c]={};for(var f in d[c])b[c][f]=d[c][f]}this.snapshots[this.backup]=[a,b]};Level.prototype.clearSnapshots=function(){this.snapshots[this.backup]=!1;this.advanceSnapshot();this.snapshots[this.backup]=!1;this.advanceSnapshot();this.snapshots[this.backup]=!1;this.retreatSnapshot()};
Level.prototype.retreatSnapshot=function(){this.backup=this.backup-1&MAXBACKUPS-1;return this.snapshots[this.backup]};Level.prototype.undo=function(){if(this.snapshots[this.backup]){for(var a=this.snapshots[this.backup][0],b=this.snapshots[this.backup][1],c=this.L,d=0;d<this.h;d++)for(var g=0;g<this.w;g++){var f=g*this.grid+d;c[f]=a[f].slice(0)}a=this.P;for(d=0;d<b.length;d++)for(var e in b[d])a[d][e]=b[d][e];this.makeModel()}else this.advanceSnapshot()};
Level.prototype.handleLoadedLevel=function(a){var b=a[0];this.P=a[1];this.w=b.length;this.h=b[0].length;this.L=Array(this.grid*this.grid);for(a=0;a<this.grid;a++)for(var c=0;c<this.grid;c++)this.L[c*this.grid+a]=[BSEA,null,0,0,0];for(a=0;a<this.h;a++)for(c=0;c<this.w;c++)b[c][a][1]=null,this.L[(c+8)*this.grid+a+8]=b[c][a];this.h+=Math.min(this.grid,16);this.w+=Math.min(this.grid,16);this.makeModel();this.loaded=1;view.changed=!0;for(b=0;b<this.P.length;b++){a=this.P[b];a.state==PUZZLER&&(heropeng=
a);a.type==PENG&&is_baby(a)&&(a.type=BABYPENG);if(a.type==OGUN||a.type==OLASER)a.thetaf+=180;a.speed=ICESPEED;a.x+=8*this.sz;a.y+=8*this.sz;a.type==CAMERA&&(a.dx+=8*this.sz,a.vx+=8*this.sz,a.dy+=8*this.sz,a.vy+=8*this.sz);a.contents=!1;a.standingon=!1;if(!(a.type in fakeObjects)){c=this.getsquare(a.x,a.y);if(0<=c){var d=this.L[c][1];if(a.contents=d)d.standingon=a;this.L[c][1]=a}a.square=c}a.numfish=0;a.bounce=0}this.backup=-1;this.snapshot();this.advanceSnapshot()};
Level.prototype.save=function(a){for(var b=0,c=0,d=1E3,g=1E3,f=0;f<this.h;f++)for(var e=0;e<this.w;e++)this.L[e*this.grid+f][0]!=BSEA&&(c=Math.max(c,f),b=Math.max(b,e),g=Math.min(g,f),d=Math.min(d,e));for(var k=[],e=d;e<=b;e++){for(var l=[],f=g;f<=c;f++){var m=this.L[e*this.grid+f];l.push([m[0],-1,m[2],m[3],m[4]])}k.push(l)}b=[];for(c=0;c<this.P.length;c++)f=this.P[c],e={},f.type!=NONE&&(e.x=f.x-this.sz*d,e.y=f.y-this.sz*g,e.dx=f.dx,e.dy=f.dy,e.vy=f.vy,e.vx=f.vx,f.type==CAMERA&&(e.dx-=d*this.sz,e.vx-=
d*this.sz,e.dy-=g*this.sz,e.vy-=g*this.sz),e.thetaf=f.thetaf,e.speed=f.speed,e.type=f.type,e.state=f.state,e.steps=f.steps,e.numfish=f.numfish,e.d=f.d,e.size=f.size,b.push(e));a?window.location="penguins.html#"+encodeURIComponent(JSON.stringify([k,b])):document.getElementById("output").innerHTML="Level="+this.levnum+"<br>"+JSON.stringify([k,b])};
Level.prototype.load=function(){var a=new XMLHttpRequest;this.loaded=!1;a.level=this;a.open("GET",path_local+"lev24.json");a.onreadystatechange=function(){4==a.readyState&&a.level.handleLoadedLevel(JSON.parse(a.responseText))};a.send();this.mode=0;this.delay=20;this.clearSnapshots()};Level.prototype.getsquare=function(a,b){var c=Math.floor(a/this.sz),d=Math.floor(b/this.sz);w=this.w;h=this.h;return 0<=c&&c<w&&0<=d&&d<h?c*this.grid+d:-1};
Level.prototype.deleteObject=function(a){a&&(a.state==PUZZLER&&this.switchpengs(),this.remove(a),a==heropeng?(this.mode=2,this.delay=10,a.bounce=0,keyPressed=!1):a.type=NONE)};Level.prototype.remove=function(a){a.standingon?a.standingon.contents=a.contents:0<=a.square&&(this.L[a.square][1]=a.contents);a.contents&&(a.contents.standingon=null);a.contents=null;a.standingon=null};
Level.prototype.trymove=function(a,b){var c=this.getsquare(a.x+a.vx*a.steps,a.y+a.vy*a.steps);if(0<=c){var d=this.squareHeight(c,.5+a.vx*a.steps*-.5/this.sz,.5+a.vy*a.steps*-.5/this.sz),g=this.squareHeight(a.square,.5+a.vx*a.steps*.5/this.sz,.5+a.vy*a.steps*.5/this.sz)+this.stackHeight(a);if(d>g+.3*this.sz||g>a.potential+5)return a.thetaf+=a.vturn*a.steps,a.potential=this.calcPotential(a),a.steps=0,a.bounce=BOUNCETIME,!1;for(var d=this.squareHeight(c,.5,.5),f=null,e=this.L[c][1];e;e=e.contents)if(d+=
objectHeights[e.type]*this.sz,g>d-5)f=e;else{if(e.type in fixed)return a.thetaf+=a.vturn*a.steps,a.potential=this.calcPotential(a),a.steps=0,a.bounce=BOUNCETIME,!1;if(a.type==PENG&&e.type==FISHPAIL){a.numfish++;PlaySound("woohoo");this.deleteObject(e);break}else if(a.type==BABYPENG&&e.type==FISHPAIL)if(PlaySound("woohoo"),this.deleteObject(e),a.state==BOPPING)for(a.state=FED;a.state==FED;)this.switchpengs();else a.numfish++;else{if(a.type==PENG&&0<a.numfish&&e.type==BABYPENG&&e.state==BOPPING)return a.numfish--,
PlaySound("woohoo"),a.thetaf+=a.vturn*a.steps,a.steps=0,a.state=FED,a.potential=this.calcPotential(a),e.state=PUZZLER,e.bounce=BOUNCETIME,e.steps=0,!1;if(e.type in moveable){e.x+=e.vx*e.steps;e.y+=e.vy*e.steps;e.thetaf+=e.vturn*e.steps;e.vx=a.vx;e.vy=a.vy;e.steps=a.steps;e.speed=a.speed;e.vturn=0;e.thetaf=a.thetaf+a.vturn*a.steps;e.potential=this.calcPotential(e)+a.potential-this.calcPotential(a);if(!this.trymove(e,b))return a.thetaf+=a.vturn*a.steps,a.bounce=BOUNCETIME,a.steps=0,a.potential=this.calcPotential(a),
!1;this.movepenguin(e,1);if(!b)return a.thetaf+=a.vturn*a.steps,a.bounce=BOUNCETIME,a.steps=0,a.potential=this.calcPotential(a),!1}else alert("Unknown type "+e.type)}}}this.remove(a);a.square=c;f?(f.contents=a,a.standingon=f):(this.L[a.square][1]=a,a.standingon=null);return!0};
Level.prototype.movepenguin=function(a,b){var c=this.sz;this.L[-1]=[BSEA,-1,0,0,0];var d=this.L[a.square],g=d[0],f=d[3],d=d[4];if(0>=a.steps){if(g.standingon||g!=BICE)return;f=mysign(f);d=mysign(d);if(0==f&&0==d)return;a.speed=ICESPEED;a.vx=-a.speed*f;a.vy=-a.speed*d;a.vturn=0;a.potential=this.calcPotential(a)}else a.x+=a.vx,a.y+=a.vy,a.thetaf+=a.vturn,a.steps-=1;0<a.steps||((a.x=c*Math.floor(a.x/c)+.5*c,a.y=c*Math.floor(a.y/c)+.5*c,a.thetaf=90*(4.5+a.thetaf/90&3),a.type==PENG&&g==BCRACKED&&(g=this.crackice(a.square),
PlaySound("boom")),f=!1,a.standingon?a.standingon.type==CHEST&&(f=!0):g==BICE&&(f=!0),f&&(a.vx||a.vy))?this.squareHeight(a.square,.5*mysign(a.vx)+.5,.5*mysign(a.vy)+.5)+this.stackHeight(a)>a.potential+5?a.vx=a.vy=a.vturn=0:(a.steps=Math.floor(c/a.speed),this.trymove(a,0)&&(a.type==BABYPENG?PlaySound("wheee"):a.vturn&&PlaySound("whooo"))):a==heropeng&&g==BEXIT?(this.mode=1,this.delay=10,keyPressed=!1,CompleteLevel(this.levnum),this.levnum++,PlaySound("audio1",!0),this.clearSnapshots()):a.type!=PENG&&
a.type!=BABYPENG||g!=BSEA?a.type==CHEST&&g==BSEA?PlaySound("splosh",!0):a.type==CHEST&&g==BCRACKED?(this.crackice(a.square),PlaySound("boom",!0)):g==BFRAGILE&&(this.L[a.square][0]=BCRACKED,this.makeModel(),PlaySound("shot",!0)):(PlaySound("splosh",!0),this.deleteObject(a)))};Level.prototype.flatten=function(a){a=this.L[a];a[2]+=Math.min(0,a[3]);a[2]+=Math.min(0,a[4]);a[3]=0;a[4]=0};Level.prototype.crackice=function(a){this.crackice_r(a);this.makeModel();return this.L[a][0]};
Level.prototype.crackice_r=function(a){if(!(0>=a)&&a in this.L){var b=this.L[a][0];if(b==BCRACKED||b==BFRAGILE){this.flatten(a);this.L[a][2]-=1;this.L[a][0]=BICE;b=this.newpenguin(a,FRAGMENT,!0);b.d=this.L[a][2]*this.sz;if(-.1>this.L[a][2])for(this.L[a][0]=BSEA;;){b=this.L[a][1];if(!b)break;if(b.type==CHEST)break;PlaySound("splosh",!0);this.deleteObject(b)}this.crackice_r(a-this.grid);this.crackice_r(a+this.grid);this.crackice_r(a+1);this.crackice_r(a-1)}}};
Level.prototype.switchpengs=function(){for(var a=!1,b=0;2>b;b++)for(var c=0;c<this.P.length;c++){var d=this.P[c];if(d.type!=NONE)if(d.state==PUZZLER)a=!0,d.state=FED;else if(d.state==FED&&a){d.state=PUZZLER;d.bounce=10;return}}};
Level.prototype.update=function(){if(this.loaded){var a=currentlyPressedKeys[KEY_LEFT],b=currentlyPressedKeys[KEY_RIGHT],c=currentlyPressedKeys[KEY_UP],d=currentlyPressedKeys[KEY_DOWN],g=currentlyPressedKeys[KEY_SPACE],f=currentlyPressedKeys[KEY_BACKSPACE]||currentlyPressedKeys[KEY_U];0<this.delay&&(this.delay--,a=c=b=d=0);0<sounddelay&&sounddelay--;if(currentlyPressedKeys[KEY_ESCAPE])window.location="http://penguinspuzzle.appspot.com";else if(currentlyPressedKeys[KEY_R])this.load();else if(0==this.delay&&
0<level.mode){if(keyPressed)if(1==this.mode)this.load(),this.delay=10,clearKeys();else if(2==this.mode)c||d?(g=this.backup,this.backup=-1,this.undo(),clearKeys(),this.backup=g,this.mode=0,this.delay=10):a||b?(this.retreatSnapshot(),this.undo(),level.mode=3,this.delay=10):f?(currentlyPressedKeys[KEY_BACKSPACE]=!1,currentlyPressedKeys[KEY_U]=!1,this.retreatSnapshot(),this.undo(),this.mode=0):currentlyPressedKeys[KEY_R]&&(currentlyPressedKeys[KEY_R]=!1,this.load(),this.mode=0);else if(3==level.mode)if(c||
d||g)level.mode=0,this.delay=10,clearKeys();else if(a||b||f)b?this.advanceSnapshot()||this.retreatSnapshot():this.retreatSnapshot()||this.advanceSnapshot(),this.undo(),this.delay=10}else if(f)currentlyPressedKeys[KEY_BACKSPACE]=!1,currentlyPressedKeys[KEY_U]=!1,this.retreatSnapshot(),this.undo();else if(!(0<level.mode))for(f=0;f<this.P.length;f++){var e=this.P[f];0<e.bounce&&e.bounce--;if(e.type!=PENG&&e.type!=BABYPENG||e.state!=PUZZLER||0!=e.steps||0<e.bounce)e.type in moveable?this.movepenguin(e):
e.type==FRAGMENT&&(e.steps++,202<e.steps&&this.deleteObject(e));else{clearKeys();g&&this.switchpengs();if(c||d||b||a){this.snapshot();this.advanceSnapshot();var k=0;c?k=0:d?k=180:a?k=270:b&&(k=90);var a=view.findUp(),k=(k+a)%360,a=c=b=d=0,l=k-e.thetaf;-179>=l&&(l+=360);179<=l&&(l-=360);1>Math.abs(l)?c=!0:1>Math.abs(l+180)?d=!0:0>l?a=!0:b=!0;e.vx=e.speed*Math.sin(3.1415*k/180);e.vy=-e.speed*Math.cos(3.1415*k/180);e.vturn=0;e.steps=Math.floor(this.sz/e.speed);d&&(e.vturn=180);a&&(e.vturn=-90);b&&(e.vturn=
90);e.vturn/=e.steps;e.potential=this.calcPotential(e);k=this.L[e.square];if(k[0]!=BICE||0==k[3]&&0==k[4])e.potential+=10;this.trymove(e,!1)}this.movepenguin(e)}}}};
Level.prototype.newpenguin=function(a,b,c){var d=a%this.grid,g=Math.floor(a/this.grid);p={};p.x=(g+.5)*this.sz;p.y=(d+.5)*this.sz;p.thetaf=0;p.d=4;p.size=8;p.state=BOPPING;p.type=b;p.speed=ICESPEED;p.steps=0;p.numfish=0;p.bounce=0;p.dx=0;p.dy=0;p.vx=0;p.vy=0;p.tol=0;p.thetah=0;p.thetac=0;p.lastz=0;p.vturn=0;if(0<=a&&!c)if(p.square=a,a=this.L[p.square][1]){for(;a.contents;)a=a.contents;p.standingon=a;a.contents=p}else this.L[p.square][1]=p;else p.square=-1;p.standingon=null;p.iden=0;p.team=0;this.P.push(p);
return p};
Level.prototype.updateView=function(){var a=1E8;if(this.loaded)if(0<this.mode&&2>=this.mode){var a=this.groundpt(heropeng),b=.003;2==this.mode&&(b=3E-4);var c=100*Math.cos(lastTime*b),b=100*Math.sin(lastTime*b);view.lookAt(a,[a[0]+c,a[1]+b,a[2]+50])}else{for(var d=0;d<this.P.length;d++){var g=this.P[d];g.type==CAMERA&&(c=g.x-heropeng.x,b=g.y-heropeng.y,c=c*c+b*b,c>a||(cam=g,a=c))}cam?(target=[cam.dx,cam.dy,cam.d],view.lookAt(target,[cam.vx,cam.vy,cam.size],!1,!0)):view.lookAt([0,0,0],[0,-200,100])}};
function World(){}World.prototype.identity=function(){this.V=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]};World.prototype.rotate=function(a){var b=Math.cos(3.1415*a/180);a=Math.sin(3.1415*a/180);this.V=mat_mult([[b,a,0,0],[-a,b,0,0],[0,0,1,0],[0,0,0,1]],this.V)};World.prototype.rotatex=function(a){var b=Math.cos(3.1415*a/180);a=Math.sin(3.1415*a/180);this.V=mat_mult([[1,0,0,0],[0,b,a,0],[0,-a,b,0],[0,0,0,1]],this.V)};
World.prototype.translate=function(a){A=[];for(var b=0;4>b;b++){for(var c=this.V[3][b],d=0;3>d;d++)c+=a[d]*this.V[d][b];A.push(c)}this.V=[this.V[0],this.V[1],this.V[2],A]};function View(){this.changed=!0;this.old_at=[0,0,0];this.old_eye=[100,100,100]}
View.prototype.lookAt=function(a,b,c,d){d&&(zoom_out&&(b=vec_add(a,vec_scale(vec_sub(b,a),1.5))),a=vec_movetowards(this.old_at,a,5),b=vec_movetowards(this.old_eye,b,5));this.L=LookAtMatrix(a,b,0);this.P=ProjectionMatrix(c);this.M=mat_mult(this.L,this.P);this.L_reflect=LookAtMatrix(a,b,1);this.M_reflect=mat_mult(this.L_reflect,this.P);this.changed=!0;this.old_at=a;this.old_eye=b};
View.prototype.findUp=function(){vec_mult([heropeng.x,heropeng.y,0,1],this.M);for(var a=0,b=0,c=0;360>c;c+=90){var d=40*Math.sin(3.1415*c/180),g=-40*Math.cos(3.1415*c/180),d=vec_mult([heropeng.x+d,heropeng.y+g,0,1],this.M),d=d[1]/d[3];if(0==c||d>a)a=d,b=c}return b};
View.prototype.findSquare=function(a,b){a/=gl.viewportWidth;b/=gl.viewportHeight;a=2*a-1;b=-1*(2*b-1);for(var c=0,d=-1,g=0,f=0,e=0;e<level.h;e++)for(var k=0;k<level.w;k++){var l=level.pt(k,e,.5,.5);l[2]=0;l.push(1);var m=vec_mult(l,this.M),l=m[0]/m[3]-a,m=m[1]/m[3]-b,l=l*l+m*m;if(0>d||l<d)d=l,c=k*level.grid+e,g=k,f=e}return[c,g,f]};
var editor=!1,path="data/",path_local="data/",gl,shader,sun_shader,shadow_shader,water_shader,expl_shader,PENG=0,TREE=1,CHEST=2,NONE=3,FRAGMENT=4,FISHPAIL=5,ROBOT=6,OGUN=7,BULLET=8,BOMB=9,DETONATOR=10,FIRE=11,SPOTLIGHT=12,WSNOWBALL=13,ROCKET=14,EXPLOSION=15,BARREL=16,CAMERA=17,SOUTHPOLE=18,SMHAT=19,OLASER=20,OMIRROR=21,OSHIELD=22,OROCKET=23,OSHIELDBLOCK=24,BABYPENG=25,BOPPING=0,WALKING=1,STILL=2,FEEDING=3,CONTROLLED=4,FED=5,PUZZLER=6,FFRAGMENT=7,FSMOKE=8,FFLASH=9,FEXPLOSION=10,FDEBRIS=11,FLASER=12,
lastMouseX=0,lastMouseY=0,level,water,sea,expl,sky,view=new View,sun_view=new View,world=new World,iceblock,tree,mainpeng,mirror_fb,models={},BICE=0,BCRACKED=1,BSEA=2,BSNOW=3,BEXIT=4,BDOOR=5,BFISHINGROD=6,BSKIS=7,BTILE=8,BPOLE=9,BBUTTON=10,BFRAGILE=11,MAXBACKUPS=64,moveable={};moveable[PENG]=!0;moveable[BABYPENG]=!0;moveable[CHEST]=!0;moveable[BOMB]=!0;moveable[FISHPAIL]=!0;var fixed={};fixed[TREE]=!0;fixed[OGUN]=!0;fixed[OLASER]=!0;var fakeObjects={};fakeObjects[CAMERA]=!0;fakeObjects[NONE]=!0;
var objectHeights={};objectHeights[PENG]=1;objectHeights[BABYPENG]=.5;objectHeights[CHEST]=1;objectHeights[TREE]=2;var BOUNCETIME=10,ICESPEED=3,KEY_Q=81,KEY_U=85,KEY_R=82,KEY_Z=90,KEY_BACKSPACE=8,KEY_SPACE=32,KEY_LEFT=37,KEY_UP=38,KEY_RIGHT=39,KEY_DOWN=40,KEY_ESCAPE=27,zoom_out=!1,frame=0,high_quality=!1,cam=null,heropeng,lastTime=0,currentlyPressedKeys={},currentlyDownKeys={},keyPressed=!1,sounddelay=0;
function mat_mult(a,b){for(var c=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]],d=0;4>d;d++)for(var g=0;4>g;g++){for(var f=0,e=0;4>e;e++)f+=a[d][e]*b[e][g];c[d][g]=f}return c}function vec_mult(a,b){for(var c=[0,0,0,0],d=0;4>d;d++){for(var g=0,f=0;4>f;f++)g+=a[f]*b[f][d];c[d]=g}return c}
function LookAtMatrix(a,b,c){if(c){var d=-20;b[2]=2*d-b[2];a[2]=2*d-a[2]}var d=vec_normal(vec_sub(a,b)),g=vec_normal(vec_cross([0,0,1],d)),f=vec_cross(d,g);g.push(-vec_dot(g,b));f.push(-vec_dot(f,b));d.push(-vec_dot(d,b));for(var e=[0,0,0,1],k=[0,0,0,0],l=0;4>l;l++)k[l]=[g[l],f[l],d[l],e[l]];c&&(d=-20,b[2]=2*d-b[2],a[2]=2*d-a[2]);return k}
function ProjectionMatrix(a){if(a)return[[.002,0,0,0],[0,.002,0,0],[0,0,.002,0],[0,0,0,1]];a=1/Math.tan(.7);var b=2E3/1990;return[[a*gl.viewportHeight/gl.viewportWidth,0,0,0],[0,a,0,0],[0,0,b,1],[0,0,10*-b,0]]}function vec_sub(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]-b[d]);return c}function vec_add(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]+b[d]);return c}function vec_scale(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]*b);return c}
function vec_dot(a,b){for(var c=0,d=0;d<a.length;d++)c+=a[d]*b[d];return c}function vec_cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}function vec_normal(a){for(var b=[],c=1/(Math.sqrt(vec_dot(a,a))+1E-4),d=0;d<a.length;d++)b.push(a[d]*c);return b}function extend(a,b){for(var c=0;c<b.length;c++)a.push(b[c])}function vec_movetowards(a,b,c){b=vec_sub(b,a);var d=Math.sqrt(vec_dot(b,b))+.001;c=Math.min(d,c);return vec_add(a,vec_scale(b,c/d))}
function Sea(a,b,c,d){var g=[],f=[];g.push([0,0,c]);f.push([0,0,1]);for(var e=0;30>=e;e++){var k=6.2832*e/30,l=Math.cos(k),k=Math.sin(k);g.push([l*b+400,k*b+400,c]);f.push([l*d,k*d,1])}this.buf=new Buffer(g,f,[]);this.t=a}Sea.prototype.draw=function(a){this.t.select();this.buf.drawfan(a)};
function Sky(a,b,c,d){for(var g=[],f=[],e=0;30>=e;e++){var k=6.283*e/30,l=Math.cos(k),k=Math.sin(k);g.push([l*b+400,k*b+400,c]);f.push([e*d/30,1,1]);g.push([l*b+400,k*b+400,b]);f.push([e*d/30,0,1])}this.buf=new Buffer(g,f,[]);this.t=a}Sky.prototype.draw=function(a){this.t.select();this.buf.drawstrip(a)};function handleMouseMove(a){lastMouseX=a.clientX;lastMouseY=a.clientY}
function handleKeyDown(a){var b=(a||window.event).keyCode;if(!(b in currentlyDownKeys&&!0==currentlyDownKeys[b]))if(currentlyDownKeys[a.keyCode]=!0,keyPressed=currentlyPressedKeys[a.keyCode]=!0,b=String.fromCharCode(a.keyCode),currentlyDownKeys[17]&&currentlyDownKeys[89])editor=!editor;else if(editor){var c=view.findSquare(lastMouseX,lastMouseY),d=c[0],g=c[1],c=c[2],f=level.L[d];switch(b){case "N":document.getElementById("output").innerHTML="";level.levnum+=1;level.load();return;case "J":document.getElementById("output").innerHTML=
"";level.levnum+=10;level.load();return;case "M":document.getElementById("output").innerHTML="";level.levnum-=1;level.load();return;case "S":f[0]=BSNOW;level.makeModel();return;case "O":f[0]=BSEA;level.makeModel();return;case "E":f[0]=BEXIT;level.makeModel();return;case "I":f[0]=BICE;level.makeModel();return;case "C":f[0]=BCRACKED;level.makeModel();return;case "V":f[0]=BFRAGILE;level.makeModel();return;case "B":level.newpenguin(d,CHEST);return;case "P":level.newpenguin(d,BABYPENG);return;case "T":level.newpenguin(d,
TREE);return;case "F":level.newpenguin(d,FISHPAIL);return;case "Q":level.deleteObject(f[1]);return;case "W":level.save(0);return;case "X":level.save(1);return;case "A":case "R":return}switch(a.keyCode){case 106:level.deleteObject(cam);return;case 107:f[2]+=.5;break;case 109:f[2]=Math.max(0,f[2]-.5);break;case 219:f[3]+=.5;.5<f[3]&&(f[3]=-.5);f[4]=0;break;case 221:f[4]+=.5;.5<f[4]&&(f[4]=-.5);f[3]=0;break;case 104:cam.vy+=10;return;case 98:cam.vy-=10;return;case 100:cam.vx-=10;return;case 102:cam.vx+=
10;return;case 105:cam.size+=10;return;case 99:cam.size-=10;return;case 101:cam.dx=g*level.sz;cam.dy=c*level.sz;cam.d=0;return;case KEY_LEFT:case KEY_RIGHT:case KEY_UP:case KEY_DOWN:case KEY_SPACE:case KEY_BACKSPACE:case 116:case 17:break;case 76:a=prompt("Paste in a level description in Json format","");level.handleLoadedLevel(JSON.parse(a));request.send();level.mode=0;level.delay=20;level.clearSnapshots();break;default:alert("Key="+a.keyCode)}level.makeModel()}}
function handleKeyUp(a){currentlyPressedKeys[a.keyCode]=!1;currentlyDownKeys[a.keyCode]=!1}function is_baby(a){return 4>a.size}function mysign(a){return.1<a?1:-.1>a?-1:0}
function Buffer(a,b,c){for(var d=0;d<b.length;d++)3>b[d].length&&b[d].push(1);for(var g=Array(b.length),d=0;d<a.length;d++)g[d]=[0,0,1];for(d=0;d<c.length;d++){var f=c[d][0],e=c[d][1],k=c[d][2],l=vec_normal(vec_cross(vec_sub(a[e],a[f]),vec_sub(a[k],a[f])));g[f]=l;g[e]=l;g[k]=l}f=[];for(d=0;d<a.length;d++)extend(f,a[d]),extend(f,b[d]),extend(f,g[d]);b=[];for(d=0;d<c.length;d++)for(g=0;3>g;g++)b.push(c[d][g]);this.ntris=c.length;this.vbuf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.vbuf);gl.bufferData(gl.ARRAY_BUFFER,
new Float32Array(f),gl.STATIC_DRAW);this.vbuf.numItems=a.length;this.ebuf=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.ebuf);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(b),gl.STATIC_DRAW);this.ebuf.numItems=b.length}
Buffer.prototype.select=function(a){gl.bindBuffer(gl.ARRAY_BUFFER,this.vbuf);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.ebuf);gl.vertexAttribPointer(a.attr_normal,3,gl.FLOAT,0,36,24);gl.vertexAttribPointer(a.attr_vertex,3,gl.FLOAT,0,36,0);gl.vertexAttribPointer(a.attr_tex,2,gl.FLOAT,0,36,12);gl.enableVertexAttribArray(a.attr_normal);gl.enableVertexAttribArray(a.attr_vertex);gl.enableVertexAttribArray(a.attr_tex)};
Buffer.prototype.draw=function(a){this.select(a);gl.drawElements(gl.TRIANGLES,this.ebuf.numItems,gl.UNSIGNED_SHORT,0)};Buffer.prototype.drawfan=function(a){this.select(a);gl.drawArrays(gl.TRIANGLE_FAN,0,this.vbuf.numItems)};Buffer.prototype.drawstrip=function(a){this.select(a);gl.drawArrays(gl.TRIANGLE_STRIP,0,this.vbuf.numItems)};
function Explosion(a){for(var b=[],c=[],d=[],g=[[0,0],[1,0],[1,1],[0,1]],f=0;300>f;f++){for(var e=b.length,k=40*(Math.random()-.5),l=40*(Math.random()-.5),m=40*Math.random(),n=0;4>n;n++)dx=g[n][0],dy=g[n][1],b.push([k,l,m]),c.push([dx,dy,1]);d.push([e,e+1,e+2]);d.push([e,e+2,e+3]);d.push([e,e+2,e+1]);d.push([e,e+3,e+2])}this.buf=new Buffer(b,c,d);this.t=a}
function Model(a,b,c,d){var g=new XMLHttpRequest,f=this;d||(d=1);f.t=b;f.loaded=!1;f.scalez=d;g.open("GET",a);g.onreadystatechange=function(){4==g.readyState&&f.handleLoaded(JSON.parse(g.responseText))};g.send();models[c]=this}Model.prototype.handleLoaded=function(a){this.A=[];for(var b=0;b<a.length;b++){for(var c=a[b][1],d=c[0],g=0;g<d.length;g++)d[g][2]*=this.scalez;this.A.push(new Buffer(c[0],c[1],c[2]))}this.loaded=!0;view.changed=!0};
Model.prototype.draw=function(a){if(this.loaded){this.t.select();for(var b=0;b<this.A.length;b++)this.A[b].draw(a)}};function getLevdata(){var a=location.hash;if(!a||null==a||10>a.length)return 0;level.handleLoadedLevel(JSON.parse(decodeURIComponent(a.substring(1))));return 1}function getLevnum(){var a=/[\?&]lev=([0-9]*)/.exec(window.location.search);if(null==a)return 0;a=parseInt(a[1]);return NaN==a?0:a}
window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a,b){return window.setTimeout(a,1E3/60)}}();function Texture(a){var b=this;b.tex=gl.createTexture();b.image=new Image;b.image.onload=function(){b.handleLoadedTexture()};b.image.src=a;this.loaded=!1}
Texture.prototype.handleLoadedTexture=function(){gl.bindTexture(gl.TEXTURE_2D,this.tex);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGB,gl.RGB,gl.UNSIGNED_BYTE,this.image);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.MIRRORED_REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.MIRRORED_REPEAT);gl.generateMipmap(gl.TEXTURE_2D);gl.bindTexture(gl.TEXTURE_2D,null);this.loaded=
!0;view.changed=!0};Texture.prototype.select=function(){this.loaded&&gl.bindTexture(gl.TEXTURE_2D,this.tex)};
function getShader(a,b){var c=document.getElementById(b);if(!c)return null;for(var d="",g=c.firstChild;g;)3==g.nodeType&&(d+=g.textContent),g=g.nextSibling;if("x-shader/x-fragment"==c.type)c=a.createShader(a.FRAGMENT_SHADER);else if("x-shader/x-vertex"==c.type)c=a.createShader(a.VERTEX_SHADER);else return null;a.shaderSource(c,d);a.compileShader(c);return a.getShaderParameter(c,a.COMPILE_STATUS)?c:(alert(a.getShaderInfoLog(c)),null)}
function Shader(a){var b=getShader(gl,a+"shader-fs");a=getShader(gl,a+"shader-vs");var c=gl.createProgram();this.shaderProgram=c;gl.attachShader(c,a);gl.attachShader(c,b);gl.linkProgram(c);gl.getProgramParameter(c,gl.LINK_STATUS)||(alert(gl.getProgramInfoLog(c)),alert("Could not initialise shaders"));this.type="Shader";this.attr_tex=gl.getAttribLocation(c,"tex");this.attr_vertex=gl.getAttribLocation(c,"vertex");this.attr_normal=gl.getAttribLocation(c,"normal");this.unif_world=gl.getUniformLocation(c,
"world");this.unif_view=gl.getUniformLocation(c,"view");this.unif_view_reflect=gl.getUniformLocation(c,"view_reflect");this.unif_color=gl.getUniformLocation(c,"color");this.unif_texture=gl.getUniformLocation(c,"texture");this.unif_texture_reflect=gl.getUniformLocation(c,"texture_reflect");this.unif_blend=gl.getUniformLocation(c,"blend")}Shader.prototype.blend=function(a,b,c,d){a||(a=0);b||(b=0);c||(c=0);d||(d=0);gl.uniform4f(this.unif_blend,a,b,c,d)};
Shader.prototype.select=function(a,b,c,d){a||(a=0);b||(b=0);c||(c=0);d||(d=0);gl.useProgram(this.shaderProgram);gl.uniform1i(this.unif_texture,0);gl.uniform4f(this.unif_blend,a,b,c,d);gl.uniform1i(this.unif_texture_reflect,1)};Shader.prototype.selectView=function(a,b){this.unifMatrix(this.unif_view,a);b&&this.unifMatrix(this.unif_view_reflect,b)};Shader.prototype.selectWorld=function(a){this.unifMatrix(this.unif_world,a)};
Shader.prototype.unifMatrix=function(a,b){for(var c=[],d=0;4>d;d++)extend(c,b[d]);c=new Float32Array(c);gl.uniformMatrix4fv(a,gl.FALSE,c)};
function Framebuffer(a,b,c){this.type="Framebuffer";this.tex=gl.createTexture();this.w=a;this.h=b;gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,this.tex);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGB,a,b,0,gl.RGB,gl.UNSIGNED_BYTE,null);gl.texParameterf(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameterf(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);this.fb=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,this.fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,
gl.TEXTURE_2D,this.tex,0);gl.activeTexture(gl.TEXTURE0);c&&(c=gl.createRenderbuffer(),gl.bindRenderbuffer(gl.RENDERBUFFER,c),gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT16,a,b),gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,c))}Framebuffer.prototype.select=function(){gl.bindFramebuffer(gl.FRAMEBUFFER,this.fb);gl.viewport(0,0,this.w,this.h)};
Framebuffer.prototype.selectTexture=function(){gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,this.tex);gl.activeTexture(gl.TEXTURE0)};function initGL(a){try{gl=a.getContext("experimental-webgl"),gl.viewportWidth=160,gl.viewportHeight=160,gl.canvas=a,a.mozImageSmoothingEnabled=!1,a.onclick=function(){toggleFullScreen()}}catch(b){}gl||(alert("Your browser does not support WebGL.  This game will not work, sorry."),window.location="http://penguinspuzzle.appspot.com")}
window.webGLStart=function(){var a=document.getElementById("mycanvas");initGL(a);gl.frontFace(gl.CW);gl.cullFace(gl.BACK);gl.enable(gl.CULL_FACE);gl.enable(gl.DEPTH_TEST);gl.depthRange(-1,1);gl.clearDepth(1);mirror_fb=new Framebuffer(1024,1024,!0);shadow_fb=new Framebuffer(1024,1024,!0);shader=new Shader("");expl_shader=new Shader("expl");shadow_shader=new Shader("shadow");sun_shader=new Shader("sun");water_shader=new Shader("water");var a=new Texture(path_local+"texmain9.bmp"),b=new Texture(path_local+
"texsecond8.bmp"),c=new Texture(path_local+"water.jpg"),d=new Texture(path_local+"clouds.jpg");level=new Level(a);level.levnum=getLevnum();getLevdata()?(level.mode=0,level.delay=20,level.clearSnapshots()):level.load();new Model(path+"iceblock.json",a,CHEST,.75);new Model(path+"tree.json",a,TREE);new Model(path+"mainpeng.json",b,PENG,.75);new Model(path+"babypeng.json",b,BABYPENG);new Model(path+"bucket.json",a,FISHPAIL);expl=new Explosion(b);sea=new Sea(c,1500,-20,15);sky=new Sky(d,1500,-20,2);document.onmousemove=
handleMouseMove;document.onkeydown=handleKeyDown;document.onkeyup=handleKeyUp;left_button=document.getElementById("left");left_button.ontouchstart=function(){handleKeyDown({keyCode:KEY_LEFT})};left_button.ontouchend=function(){handleKeyUp({keyCode:KEY_LEFT})};left_button=document.getElementById("right");left_button.ontouchstart=function(){handleKeyDown({keyCode:KEY_RIGHT})};left_button.ontouchend=function(){handleKeyUp({keyCode:KEY_RIGHT})};left_button=document.getElementById("up");left_button.ontouchstart=
function(){handleKeyDown({keyCode:KEY_UP})};left_button.ontouchend=function(){handleKeyUp({keyCode:KEY_UP})};left_button=document.getElementById("down");left_button.ontouchstart=function(){handleKeyDown({keyCode:KEY_DOWN})};left_button.ontouchend=function(){handleKeyUp({keyCode:KEY_DOWN})};left_button=document.getElementById("switch");left_button.ontouchstart=function(){handleKeyDown({keyCode:KEY_SPACE})};left_button.ontouchend=function(){handleKeyUp({keyCode:KEY_SPACE})};view.lookAt([0,0,0],[0,-100,
50]);sun_view.lookAt([540,540,0],[570,520,40],1);tick();toggleFullScreen()};
function drawScene(){check_window_size();var a=view.changed;editor||frame++;currentlyPressedKeys[KEY_Q]&&(high_quality=!high_quality,currentlyPressedKeys[KEY_Q]=!1);currentlyPressedKeys[KEY_Z]&&(zoom_out=!zoom_out,currentlyPressedKeys[KEY_Z]=!1);high_quality&&(gl.colorMask(!0,!0,!0,!0),shadow_fb.select(),gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT),world.identity(),sun_shader.select(),sun_shader.selectView(sun_view.M),sun_shader.selectWorld(world.V),level.drawTiles(sun_shader),level.drawObjects(sun_shader,
sun_view),level.drawObjects(sun_shader,sun_view,!0),gl.finish());gl.clearColor(129/288,168/288,.71875,1);high_quality&&(mirror_fb.select(),gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT),world.identity(),shader.select(1E-4*frame),shader.selectView(view.M_reflect),shader.selectWorld(world.V),sky.draw(shader),shader.select(),level.drawObjects(shader,view),level.drawObjects(shader,view,!0),world.identity(),shader.selectWorld(world.V),level.drawTiles(shader),gl.finish());gl.bindFramebuffer(gl.FRAMEBUFFER,
null);gl.viewport(0,0,gl.viewportWidth,gl.viewportHeight);3==level.mode?(gl.clearColor(0,129,0,1),gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT),gl.colorMask(!1,!0,!1,!0)):(gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT),gl.colorMask(!0,!0,!0,!0));shadow_fb.selectTexture();world.identity();var b=shader;high_quality&&(b=shadow_shader);b.select();b.selectView(view.M,sun_view.M);b.selectWorld(world.V);level.drawTiles(b);shader.select(1E-4*frame);shader.selectView(view.M);shader.selectWorld(world.V);
sky.draw(shader);shader.select();level.drawObjects(shader,view);mirror_fb.selectTexture();world.identity();high_quality&&(water_shader.select(4E-4*frame,8E-4*frame,6.8E-4*-frame,.003*-frame*.4),water_shader.selectView(view.M,view.M_reflect),shader.selectWorld(world.V),sea.draw(water_shader));shader.select();shader.selectView(view.M);high_quality&&(gl.depthMask(!1),gl.blendEquation(gl.FUNC_ADD),gl.enable(gl.BLEND),gl.blendFunc(gl.ONE,gl.ONE_MINUS_CONSTANT_ALPHA),gl.blendColor(0,0,0,.7));level.drawObjects(shader,
view,!0);high_quality&&(gl.blendFunc(gl.SRC_ALPHA,gl.ONE),expl_shader.select(),expl_shader.selectView(view.M),level.drawFragments(expl_shader));gl.disable(gl.BLEND);gl.depthMask(!0);gl.finish();a&&(view.changed=!1)}function tick(){requestAnimFrame(tick);level.updateView();level.update();drawScene();animate()};
